/**
 * Lazy loader for the WHO LMS tables (generated by `npm run who-data`). Each table is its own
 * dynamic-import chunk (≈15–30 KB gzip each) so the main bundle stays small; results are memoised.
 */
import type { LmsTable } from './lms';

export type GrowthIndicator = 'weight' | 'length' | 'head';
export const GROWTH_INDICATORS: readonly GrowthIndicator[] = ['weight', 'length', 'head'];

export type WhoTables = Record<GrowthIndicator, LmsTable>;

/** Last age (days) covered by the WHO 0–5 y standards tables. */
export const WHO_MAX_AGE_DAYS = 1826;

const loaders: Record<GrowthIndicator, () => Promise<{ default: LmsTable }>> = {
  weight: () => import('./data/weightForAge'),
  length: () => import('./data/lengthForAge'),
  head: () => import('./data/headCircumferenceForAge'),
};

const cache = new Map<GrowthIndicator, Promise<LmsTable>>();

/** Loads (once) the WHO LMS table for an indicator. A failed load is not cached, so it can be retried. */
export function loadWhoTable(indicator: GrowthIndicator): Promise<LmsTable> {
  let pending = cache.get(indicator);
  if (!pending) {
    pending = loaders[indicator]().then(
      (mod) => mod.default,
      (error: unknown) => {
        cache.delete(indicator);
        throw error;
      },
    );
    cache.set(indicator, pending);
  }
  return pending;
}

/** Loads all three tables in parallel. */
export async function loadWhoTables(): Promise<WhoTables> {
  const [weight, length, head] = await Promise.all(GROWTH_INDICATORS.map(loadWhoTable));
  if (!weight || !length || !head) throw new Error('WHO tables failed to load');
  return { weight, length, head };
}
